<a href="https://colab.research.google.com/github/VINUVPOTTY/knn/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('/lung_cancer_examples.csv')
df

           Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0          John         Wick   35       3      5       4       1
1          John  Constantine   27      20      2       5       1
2        Camela     Anderson   30       0      5       2       0
3          Alex       Telles   28       0      8       1       0
4         Diego     Maradona   68       4      5       6       1
5     Cristiano      Ronaldo   34       0     10       0       0
6        Mihail          Tal   58      15     10       0       0
7         Kathy        Bates   22      12      5       2       0
8        Nicole       Kidman   45       2      6       0       0
9           Ray      Milland   52      18      4       5       1
10      Fredric        March   33       4      8       0       0
11          Yul      Brynner   18      10      6       3       0
12         Joan     Crawford   25       2      5       1       0
13         Jane        Wyman   28      20      2       8       1
14         Anna      Magnani   34      25      4       8       1
15   Katharine       Hepburn   39      18      8       1       0
16   Katharine       Hepburn   42      22      3       5       1
17       Barbra    Streisand   19      12      8       0       0
18      Maggie         Smith   62       5      4       3       1
19      Glenda       Jackson   73      10      7       6       1
20        Jane         Fonda   55      15      1       3       1
21  Maximilian        Schell   33       8      8       1       0
22     Gregory          Peck   22      20      6       2       0
23      Sidney       Poitier   44       5      8       1       0
24         Rex      Harrison   77       3      2       6       1
25         Lee        Marvin   21      20      5       3       0
26        Paul      Scofield   37      15      6       2       0
27         Rod       Steiger   34      12      8       0       0
28        John         Wayne   55      20      1       4       1
29        Gene       Hackman   40      20      2       7       1
30      Marlon        Brando   36      13      5       2       0
31        Jack        Lemmon   56      20      3       3       1
32        Jack     Nicholson   47      15      1       8       1
33       Peter        Finch    62      25      3       4       1
34     Richard      Dreyfuss   26      10      7       2       0
35      Dustin       Hoffman   25      20      8       2       0
36       Henry        Henry    59      20      3       4       1
37      Robert        Duvall   62      15      5       5       1
38       Ellen       Burstyn   33      25      8       2       0
39        Faye       Dunaway   37      10      5       3       0
40       Diane        Keaton   50      20      2       4       1
41        Jane         Fonda   47      12      8       0       0
42       Sally         Field   69      20      5       4       1
43       Sissy        Spacek   63      20      4       5       1
44     Jessica         Lange   39      15      7       2       0
45     Gwyneth       Paltrow   21      20      8       3       0
46       Halle         Berry   31      20      9       4       0
47      Nicole        Kidman   28      10      4       1       0
48    Charlize        Theron   53      20      6       3       1
49   Katharine       Hepburn   62      20      5       6       1
50   Katharine       Hepburn   42      12      6       2       0
51      Barbra     Streisand   44      30      1       6       1
52      Maggie         Smith   26      34      1       8       1
53      Glenda       Jackson   35      20      5       1       0
54      Ernest      Borgnine   26      13      6       1       0
55        Alec      Guinness   77      20      5       4       1
56    Charlton        Heston   75      15      3       5       1
57     Gregory          Peck   43      30      3       8       1
58      Sidney       Poitier   51      25      9       0       0

In [ ]:
df.head()

     Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0    John         Wick   35       3      5       4       1
1    John  Constantine   27      20      2       5       1
2  Camela     Anderson   30       0      5       2       0
3    Alex       Telles   28       0      8       1       0
4   Diego     Maradona   68       4      5       6       1

In [ ]:
df.tail()

         Name   Surname  Age  Smokes  AreaQ  Alkhol  Result
54    Ernest   Borgnine   26      13      6       1       0
55      Alec   Guinness   77      20      5       4       1
56  Charlton     Heston   75      15      3       5       1
57   Gregory       Peck   43      30      3       8       1
58    Sidney    Poitier   51      25      9       0       0

In [ ]:
df.isna().sum()

Name       0
Surname    0
Age        0
Smokes     0
AreaQ      0
Alkhol     0
Result     0
dtype: int64

In [ ]:
df.dtypes

Name       object
Surname    object
Age         int64
Smokes      int64
AreaQ       int64
Alkhol      int64
Result      int64
dtype: object

In [ ]:
df.drop(['Name','Surname'],axis=1,inplace=True)

In [ ]:
x = df.iloc[:, :-1].values
x

array([[35,  3,  5,  4],
       [27, 20,  2,  5],
       [30,  0,  5,  2],
       [28,  0,  8,  1],
       [68,  4,  5,  6],
       [34,  0, 10,  0],
       [58, 15, 10,  0],
       [22, 12,  5,  2],
       [45,  2,  6,  0],
       [52, 18,  4,  5],
       [33,  4,  8,  0],
       [18, 10,  6,  3],
       [25,  2,  5,  1],
       [28, 20,  2,  8],
       [34, 25,  4,  8],
       [39, 18,  8,  1],
       [42, 22,  3,  5],
       [19, 12,  8,  0],
       [62,  5,  4,  3],
       [73, 10,  7,  6],
       [55, 15,  1,  3],
       [33,  8,  8,  1],
       [22, 20,  6,  2],
       [44,  5,  8,  1],
       [77,  3,  2,  6],
       [21, 20,  5,  3],
       [37, 15,  6,  2],
       [34, 12,  8,  0],
       [55, 20,  1,  4],
       [40, 20,  2,  7],
       [36, 13,  5,  2],
       [56, 20,  3,  3],
       [47, 15,  1,  8],
       [62, 25,  3,  4],
       [26, 10,  7,  2],
       [25, 20,  8,  2],
       [59, 20,  3,  4],
       [62, 15,  5,  5],
       [33, 25,  8,  2],
       [37, 10,  5,  3],
       [50, 20,  2,  4],
       [47, 12,  8,  0],
       [69, 20,  5,  4],
       [63, 20,  4,  5],
       [39, 15,  7,  2],
       [21, 20,  8,  3],
       [31, 20,  9,  4],
       [28, 10,  4,  1],
       [53, 20,  6,  3],
       [62, 20,  5,  6],
       [42, 12,  6,  2],
       [44, 30,  1,  6],
       [26, 34,  1,  8],
       [35, 20,  5,  1],
       [26, 13,  6,  1],
       [77, 20,  5,  4],
       [75, 15,  3,  5],
       [43, 30,  3,  8],
       [51, 25,  9,  0]])

In [ ]:
y = df.iloc[:, -1].values
y

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0])

In [ ]:
#Traininig and testing the data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30,random_state=42 )
x_train
x_test

array([[35,  3,  5,  4],
       [34,  0, 10,  0],
       [26, 10,  7,  2],
       [28, 20,  2,  8],
       [21, 20,  8,  3],
       [35, 20,  5,  1],
       [43, 30,  3,  8],
       [21, 20,  5,  3],
       [28, 10,  4,  1],
       [25,  2,  5,  1],
       [62, 20,  5,  6],
       [28,  0,  8,  1],
       [59, 20,  3,  4],
       [56, 20,  3,  3],
       [45,  2,  6,  0],
       [19, 12,  8,  0],
       [58, 15, 10,  0],
       [68,  4,  5,  6]])

In [ ]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
scalar.fit(x_train)
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)
x_train

array([[-1.15393627, -0.43269425,  0.40496913, -1.08797778],
       [ 1.7796194 , -0.84848639,  0.80993827,  1.1649055 ],
       [-0.52977549, -0.43269425,  0.        , -0.63740112],
       [-0.15527902, -0.57129163,  0.40496913, -0.63740112],
       [-0.34252726, -0.1554995 ,  0.80993827, -0.63740112],
       [ 2.02928371,  0.53748739,  0.        ,  0.26375219],
       [-0.34252726,  0.26029264,  1.2149074 , -1.08797778],
       [ 0.46888176,  0.26029264, -0.40496913,  0.71432885],
       [-0.65460765, -0.57129163,  1.2149074 , -1.53855444],
       [-0.46735941, -0.1554995 ,  0.40496913, -0.63740112],
       [-0.15527902,  0.81468215, -0.80993827,  0.71432885],
       [ 2.02928371, -1.81866804, -1.2149074 ,  1.1649055 ],
       [ 1.09304254,  1.23047428, -0.80993827,  0.26375219],
       [ 1.90445155, -0.1554995 , -0.80993827,  0.71432885],
       [ 0.15680137, -0.57129163,  1.2149074 , -1.53855444],
       [-1.6532649 , -0.84848639,  0.40496913, -0.18682447],
       [ 0.15680137, -0.1554995 , -1.61987654,  2.06605882],
       [-1.15393627,  2.47785069, -1.61987654,  2.06605882],
       [ 0.3440496 ,  0.53748739, -1.2149074 ,  0.26375219],
       [ 1.09304254, -0.1554995 ,  0.        ,  0.71432885],
       [-0.28011118,  0.53748739, -1.2149074 ,  1.61548216],
       [ 1.15545862,  0.53748739, -0.40496913,  0.71432885],
       [-1.09152019,  0.53748739, -1.2149074 ,  0.71432885],
       [-0.71702373, -1.12568114,  1.2149074 , -1.08797778],
       [-0.90427196, -2.23446017,  0.        , -0.63740112],
       [-0.84185588,  0.53748739,  1.61987654,  0.26375219],
       [-0.46735941, -0.84848639,  0.        , -0.18682447],
       [-1.21635235,  0.53748739,  1.2149074 , -0.63740112],
       [-0.03044687, -1.54147328,  1.2149074 , -1.08797778],
       [ 0.53129784,  0.53748739,  0.40496913, -0.18682447],
       [-0.71702373, -1.68007066,  1.2149074 , -1.53855444],
       [-1.40360058,  0.53748739,  0.40496913, -0.63740112],
       [ 1.09304254, -1.54147328, -0.40496913, -0.18682447],
       [ 0.40646568,  1.23047428,  1.61987654, -1.53855444],
       [ 0.65612999, -0.1554995 , -1.61987654, -0.18682447],
       [-1.40360058, -0.57129163,  0.        , -0.63740112],
       [ 1.52995508,  0.53748739,  0.        ,  0.26375219],
       [-0.65460765,  1.23047428, -0.40496913,  2.06605882],
       [ 0.65612999,  0.53748739, -1.61987654,  0.26375219],
       [-0.03044687,  1.92346117, -1.61987654,  1.1649055 ],
       [-0.71702373,  1.23047428,  1.2149074 , -0.63740112]])

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
ann=Sequential()
#input layer
ann.add(Dense(units=4,activation='relu'))
#hidden layer
ann.add(Dense(units=10,activation='relu'))
ann.add(Dense(units=6,activation='relu'))
#output layer
ann.add(Dense(units=1,activation='sigmoid'))

In [ ]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
ann.fit(x_train,y_train,epochs=100)

Epoch 1/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 0.6311 - loss: 0.6746
Epoch 2/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6474 - loss: 0.6671
Epoch 3/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6682 - loss: 0.6656
Epoch 4/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6949 - loss: 0.6601
Epoch 5/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7215 - loss: 0.6583
Epoch 6/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7170 - loss: 0.6569
Epoch 7/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9200 - loss: 0.6507
Epoch 8/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9466 - loss: 0.6497
Epoch 9/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9466 - loss: 0.6499
Epoch 10/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9571 - loss: 0.6440
Epoch 11/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9466 - loss: 0.6371
Epoch 12/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9466 - loss: 0.6351
Epoch 13/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9675 - loss: 0.6275
Epoch 14/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9466 - loss: 0.6298
Epoch 15/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9466 - loss: 0.6283
Epoch 16/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9571 - loss: 0.6229
Epoch 17/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9571 - loss: 0.6183
Epoch 18/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9466 - loss: 0.6165
Epoch 19/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9571 - loss: 0.6069
Epoch 20/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9466 - loss: 0.6077
Epoch 21/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9571 - loss: 0.6078
Epoch 22/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9466 - loss: 0.6066
Epoch 23/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9466 - loss: 0.5978
Epoch 24/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9466 - loss: 0.5972
Epoch 25/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9466 - loss: 0.5942
Epoch 26/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9571 - loss: 0.5932
Epoch 27/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9571 - loss: 0.5869
Epoch 28/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9571 - loss: 0.5754
Epoch 29/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9466 - loss: 0.5816
Epoch 30/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9466 - loss: 0.5839
Epoch 31/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9466 - loss: 0.5707
Epoch 32/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9733 - loss: 0.5635
Epoch 33/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9837 - loss: 0.5610
Epoch 34/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9837 - loss: 0.5579
Epoch 35/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9733 - loss: 0.5557
Epoch 36/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9733 - loss: 0.5491
Epoch 37/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9733 - loss: 0.5428
Epoch 38/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9837 - loss: 0.5284
Epoch 39/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9733 - loss: 0.5349
Epoch 40/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9733 - loss: 0.5291
Epoch 41/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9837 - loss: 0.5202
Epoch 42/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9733 - loss: 0.5192
Epoch 43/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9733 - loss: 0.5208
Epoch 44/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9733 - loss: 0.5116
Epoch 45/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9837 - loss: 0.5047
Epoch 46/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9837 - loss: 0.4926
Epoch 47/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9837 - loss: 0.4932
Epoch 48/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9733 - loss: 0.4925
Epoch 49/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9837 - loss: 0.4821
Epoch 50/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9733 - loss: 0.4880
Epoch 51/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9837 - loss: 0.4677
Epoch 52/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9733 - loss: 0.4744
Epoch 53/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9733 - loss: 0.4721
Epoch 54/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9837 - loss: 0.4497
Epoch 55/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9733 - loss: 0.4618
Epoch 56/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9837 - loss: 0.4448
Epoch 57/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9733 - loss: 0.4427
Epoch 58/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9733 - loss: 0.4396
Epoch 59/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9733 - loss: 0.4375
Epoch 60/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9733 - loss: 0.4358
Epoch 61/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9733 - loss: 0.4289
Epoch 62/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9733 - loss: 0.4226
Epoch 63/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9733 - loss: 0.4144
Epoch 64/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9733 - loss: 0.4148
Epoch 65/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9733 - loss: 0.4123
Epoch 66/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9733 - loss: 0.4013
Epoch 67/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9733 - loss: 0.3921
Epoch 68/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9733 - loss: 0.3865
Epoch 69/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9733 - loss: 0.3856
Epoch 70/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9733 - loss: 0.3772
Epoch 71/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9837 - loss: 0.3739
Epoch 72/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9733 - loss: 0.3693
Epoch 73/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9733 - loss: 0.3604
Epoch 74/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9837 - loss: 0.3562
Epoch 75/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9837 - loss: 0.3526
Epoch 76/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9733 - loss: 0.3585
Epoch 77/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9733 - loss: 0.3514
Epoch 78/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9733 - loss: 0.3494
Epoch 79/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9733 - loss: 0.3297
Epoch 80/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9733 - loss: 0.3327
Epoch 81/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9733 - loss: 0.3222
Epoch 82/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9733 - loss: 0.3302
Epoch 83/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9733 - loss: 0.3196
Epoch 84/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9733 - loss: 0.3180
Epoch 85/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9733 - loss: 0.3072
Epoch 86/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9733 - loss: 0.3051
Epoch 87/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9733 - loss: 0.2965
Epoch 88/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9837 - loss: 0.2882
Epoch 89/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9733 - loss: 0.2916
Epoch 90/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9733 - loss: 0.2807
Epoch 91/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9733 - loss: 0.2773
Epoch 92/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9733 - loss: 0.2749
Epoch 93/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9733 - loss: 0.2655
Epoch 94/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9837 - loss: 0.2602
Epoch 95/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9733 - loss: 0.2675
Epoch 96/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9733 - loss: 0.2540
Epoch 97/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9837 - loss: 0.2422
Epoch 98/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9733 - loss: 0.2457
Epoch 99/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9733 - loss: 0.2440
Epoch 100/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9733 - loss: 0.2399

In [ ]:
ann.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 6)              │            66 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             7 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 431 (1.69 KB)

 Trainable params: 143 (572.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 288 (1.13 KB)

In [ ]:
ann.evaluate(x_test,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step - accuracy: 0.8889 - loss: 0.3158

[0.31576281785964966, 0.8888888955116272]

In [ ]:
y_pred=ann.predict(scalar.transform([[35,3,5,4]]))
if y_pred>0.5:
  print("lungs cancer")
else:
  print("no cancer")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
no cancer

In [1]:
!git config --global user.email "vinuvpoty@gmail.com"
!git config --global user.name "Vinayak v potty"

In [4]:
!git clone https://ghp_vSyVrIYSuajLfqulHlAnuYwWRBuGAt16GuB7@github.com/VINUVPOTTY/knn.git

Cloning into 'knn'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (13/13), done.
Receiving objects: 100% (15/15), 53.81 KiB | 4.48 MiB/s, done.
Resolving deltas: 100% (3/3), done.
remote: Total 15 (delta 3), reused 0 (delta 0), pack-reused 0 (from 0)